import papi, { logger } from '@papi/frontend';
import {
  Button,
  Spinner,
  useEvent,
  usePromise,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  MarkdownRenderer,
  Alert,
  AlertTitle,
  AlertDescription,
} from 'platform-bible-react';
import { ReactNode, useCallback, useEffect, useMemo, useReducer, useRef, useState } from 'react';
import { useSetting } from '@papi/frontend/react';
import { WebViewProps } from '@papi/core';
import { getErrorMessage } from 'platform-bible-utils';
import { AlertCircle } from 'lucide-react';
import ProjectTable from './project-table.component';
import { expandServerConfiguration } from '../auth/server-configuration.model';

globalThis.webViewComponent = function ScriptureForgeHome({
  iconUrl,
  useWebViewState,
}: WebViewProps) {
  const isMounted = useRef(false);
  useEffect(() => {
    isMounted.current = true;
    return () => {
      isMounted.current = false;
    };
  });

  const [serverConfigurationCondensed] = useSetting('scriptureForge.serverConfiguration', 'live');
  const serverConfiguration = useMemo(
    () => expandServerConfiguration(serverConfigurationCondensed),
    [serverConfigurationCondensed],
  );

  const [sessionChangeListener, didChangeSession] = useReducer((x) => x + 1, 0);
  useEvent(
    papi.network.getNetworkEvent<undefined>('scriptureForge.sessionChange'),
    didChangeSession,
  );

  // If we're doing something with login state such that we shouldn't allow the user to log in or out
  const [isLoginBusy, setIsLoginBusy] = useState(false);
  const [loginErrorMessage, setLoginErrorMessage] = useState('');

  const [isLoggedIn] = usePromise(
    useCallback(async () => {
      // Needed to use this in the function to add it to the dependency array to get login info again
      // on session change
      // eslint-disable-next-line no-unused-expressions
      sessionChangeListener;

      setLoginErrorMessage('');
      setIsLoginBusy(true);
      let isLoggedInNew = false;
      try {
        isLoggedInNew = await papi.commands.sendCommand('scriptureForge.isLoggedIn');
      } catch (e) {
        const errorMessage = `Scripture Forge failed to determine if you are logged in. ${getErrorMessage(e)}`;
        logger.warn(errorMessage);
        if (isMounted.current) setLoginErrorMessage(errorMessage);
      }
      if (isMounted.current) setIsLoginBusy(false);
      return isLoggedInNew;
    }, [sessionChangeListener]),
    false,
  );

  /**
   * Logs in or out
   *
   * @param shouldLogIn `true` to log in; `false` to log out
   */
  const logInOrOut = async (shouldLogIn: boolean) => {
    try {
      setLoginErrorMessage('');
      setIsLoginBusy(true);
      await (shouldLogIn
        ? papi.commands.sendCommand('scriptureForge.login')
        : papi.commands.sendCommand('scriptureForge.logout'));
    } catch (e) {
      const errorMessage = `Scripture Forge failed to log ${shouldLogIn ? 'in' : 'out'}. ${getErrorMessage(e)}`;
      logger.warn(errorMessage);
      if (isMounted.current) setLoginErrorMessage(errorMessage);
    }
    if (isMounted.current) setIsLoginBusy(false);
  };

  let logInOrOutButtonContents: ReactNode = isLoggedIn ? 'Log out' : 'Log in';
  if (isLoginBusy) logInOrOutButtonContents = <Spinner className="tw-h-4 tw-w-4" />;

  return !isLoggedIn ? (
    <div className="tw-flex tw-bg-muted/50 tw-h-screen tw-items-center tw-justify-center">
      <Card className="tw-max-w-md">
        <CardHeader>
          <CardTitle>AI Drafts extension</CardTitle>
          <CardDescription>By Scripture Forge</CardDescription>
        </CardHeader>
        <CardContent>
          <MarkdownRenderer
            anchorTarget="_blank"
            markdown={`
This extension allows you to use limited features of Scripture Forge:

- View the list of projects you can see in Scripture Forge
- Open drafts that have already been generated by AI for a project in Scripture Forge
              `}
          />

          <Button
            onClick={() => {
              logInOrOut(!isLoggedIn);
            }}
            disabled={isLoginBusy}
            variant={isLoggedIn ? 'ghost' : 'default'}
          >
            {logInOrOutButtonContents}
          </Button>
          {loginErrorMessage && (
            <Alert variant="destructive">
              <AlertCircle className="tw-h-4 tw-w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{loginErrorMessage}</AlertDescription>
            </Alert>
          )}

          <MarkdownRenderer
            anchorTarget="_blank"
            markdown={`
An administrator must connect a project in Scripture Forge and generate an AI draft
before you can interact with it in this extension.

Visit [Scripture Forge](${serverConfiguration.scriptureForge.domain}) to access
its full set of features.
              `}
          />
        </CardContent>
      </Card>
    </div>
  ) : (
    <div className="tw-flex tw-flex-col tw-h-screen">
      <div className="tw-flex tw-px-4 tw-gap-2 tw-pt-2 tw-pb-1">
        <img src={iconUrl} alt="Scripture Forge Logo" className="tw-w-5" />
        <div className="tw-text-sm tw-font-semibold">Scripture Forge</div>
      </div>
      <div className="tw-flex tw-items-center tw-justify-between tw-w-full tw-px-4 tw-pb-3">
        <div className="tw-text-2xl tw-font-semibold">Auto Drafts</div>
        <Button
          onClick={() => {
            logInOrOut(!isLoggedIn);
          }}
          disabled={isLoginBusy}
          variant={isLoggedIn ? 'ghost' : 'default'}
        >
          {logInOrOutButtonContents}
        </Button>
      </div>
      {loginErrorMessage && (
        <Alert variant="destructive">
          <AlertCircle className="tw-h-4 tw-w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{loginErrorMessage}</AlertDescription>
        </Alert>
      )}
      <div className="tw-flex-1 tw-overflow-auto tw-pt-2 tw-px-1">
        <ProjectTable
          serverConfiguration={serverConfiguration}
          useWebViewState={useWebViewState}
          onDidLogOut={didChangeSession}
        />
      </div>
    </div>
  );
};
